import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="google-site-verification"
          content="3Zrude9mrTe4FCdHAqRdcWRGkmuWeDkZWls4MG8FOMw"
        />
        <title>Your webhook Data</title>
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
